### ISSUE TITLE
Date Left not setable

### ISSUE THREAD

**Issue by netfreak98** [inex/IXP-Manager#456]
Currently it is not possible to mark a customer as left. After pressing the "Save Changes" button I get "Customer successfully edited." but the "left" field is still empty.

**Comment by barryo** [comment]
I’m pretty sure I did this recently without issue. 

What version are you running?

**Comment by listerr** [comment]
Possibly duplicate of #438 ?
I had same issue but was fixed.

**Comment by barryo** [comment]
Thanks @listerr - looks like a dub alright. Fixed in master.

**Comment by netfreak98** [comment]
Hi, the Problem still persists for us using manager version V4.8.0

**Comment by netfreak98** [comment]
Can you please reopen this issue?

**Comment by nickhilliard** [comment]
@netfreak98 the problem exists in 4.8.0 but was fixed in commit d1453d5b17418b1eed567238ce9ad8f1c9cd7a36.  We're planning to release 4.9.0 shortly, which will have the fix included.

**Comment by netfreak98** [comment]
I can confirm, it is fixed now. Thanks! :)
