### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by gizmo15** [inex/IXP-Manager#696]
Hi,
I just installed the last release and when i access to ixp manager with Firefox or Chromium i have this message on the login page :
500 Server Error :: Array and string offset access syntax with curly braces is deprecated

My configuration :
FreeBSD 12.1
php74-7.4.15
php74-composer-1.10.20
php74-ctype-7.4.15
php74-curl-7.4.15
php74-dom-7.4.15
php74-fileinfo-7.4.15
php74-filter-7.4.15
php74-gd-7.4.15
php74-gettext-7.4.15
php74-gmp-7.4.15
php74-iconv-7.4.15
php74-intl-7.4.15
php74-json-7.4.15
php74-mbstring-7.4.15
php74-mysqli-7.4.15
php74-openssl-7.4.15
php74-pcntl-7.4.15
php74-pdo-7.4.15
php74-pdo_mysql-7.4.15
php74-pear-1.10.12
php74-pear-PHP_Parser-0.2.2
php74-phar-7.4.15
php74-posix-7.4.15
php74-session-7.4.15
php74-simplexml-7.4.15
php74-sockets-7.4.15
php74-tokenizer-7.4.15
php74-xml-7.4.15
php74-zlib-7.4.15
mysql80-client-8.0.23
mysql80-server-8.0.23

With nginx.

I follow those instructions : https://docs.ixpmanager.org/install/manually/

Thanks for the help!

**Comment by nickhilliard** [comment]
what error are you seeing in laravel.log?

**Comment by gizmo15** [comment]
The full error :
`[2021-03-04 19:27:50] production.ERROR: Array and string offset access syntax with curly braces is deprecated {"exception":"[object] (ErrorException(code: 0): Array and string offset access syntax with curly braces is deprecated at /mnt/external/www/ixpmanager/vendor/ezyang/htmlpurifier/library/HTMLPurifier/TagTransform/Font.php:78)
[stacktrace]
#0 /mnt/external/www/ixpmanager/vendor/composer/ClassLoader.php(444): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8192, 'Array and strin...', '/mnt/external/w...', 78, Array)
#1 /mnt/external/www/ixpmanager/vendor/composer/ClassLoader.php(444): include()
#2 /mnt/external/www/ixpmanager/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/mnt/external/w...')
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('HTMLPurifier_Ta...')
#4 /mnt/external/www/ixpmanager/vendor/ezyang/htmlpurifier/library/HTMLPurifier/HTMLModule/Tidy/XHTMLAndHTML4.php(15): spl_autoload_call('HTMLPurifier_Ta...')
#5 /mnt/external/www/ixpmanager/vendor/ezyang/htmlpurifier/library/HTMLPurifier/HTMLModule/Tidy.php(46): HTMLPurifier_HTMLModule_Tidy_XHTMLAndHTML4->makeFixes()
#6 /mnt/external/www/ixpmanager/vendor/ezyang/htmlpurifier/library/HTMLPurifier/HTMLModuleManager.php(293): HTMLPurifier_HTMLModule_Tidy->setup(Object(HTMLPurifier_Config))
#7 /mnt/external/www/ixpmanager/vendor/ezyang/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php(220): HTMLPurifier_HTMLModuleManager->setup(Object(HTMLPurifier_Config))
#8 /mnt/external/www/ixpmanager/vendor/ezyang/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php(195): HTMLPurifier_HTMLDefinition->processModules(Object(HTMLPurifier_Config))
#9 /mnt/external/www/ixpmanager/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Definition.php(51): HTMLPurifier_HTMLDefinition->doSetup(Object(HTMLPurifier_Config))
#10 /mnt/external/www/ixpmanager/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php(515): HTMLPurifier_Definition->setup(Object(HTMLPurifier_Config))
#11 /mnt/external/www/ixpmanager/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php(415): HTMLPurifier_Config->getDefinition('HTML', false, false)
#12 /mnt/external/www/ixpmanager/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Generator.php(74): HTMLPurifier_Config->getHTMLDefinition()
#13 /mnt/external/www/ixpmanager/vendor/ezyang/htmlpurifier/library/HTMLPurifier.php(158): HTMLPurifier_Generator->__construct(Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#14 /mnt/external/www/ixpmanager/vendor/luketowers/purifier/src/Purifier.php(257): HTMLPurifier->purify('Invalid usernam...', Object(HTMLPurifier_Config))
#15 /mnt/external/www/ixpmanager/vendor/luketowers/purifier/src/helpers.php(6): LukeTowers\\Purifier\\Purifier->clean('Invalid usernam...', NULL)
#16 /mnt/external/www/ixpmanager/app/Utils/View/Alert/Container.php(100): clean('Invalid usernam...')
#17 [internal function]: IXP\\Utils\\View\\Alert\\Container::html()
#18 /mnt/external/www/ixpmanager/vendor/foil/foil/src/Kernel/Command.php(168): call_user_func_array(Array, Array)
#19 /mnt/external/www/ixpmanager/vendor/foil/foil/src/Kernel/Command.php(195): Foil\\Kernel\\Command->execute('alerts', Array, Array)
#20 [internal function]: Foil\\Kernel\\Command->doRun('alerts')
#21 /mnt/external/www/ixpmanager/vendor/foil/foil/src/Kernel/Command.php(181): call_user_func_array(Array, Array)
#22 [internal function]: Foil\\Kernel\\Command->doRunIsolated('alerts')
#23 /mnt/external/www/ixpmanager/vendor/foil/foil/src/Kernel/Command.php(104): call_user_func_array(Array, Array)
#24 [internal function]: Foil\\Kernel\\Command->run('alerts')
#25 /mnt/external/www/ixpmanager/vendor/foil/foil/src/Template/Template.php(164): call_user_func_array(Array, Array)
#26 [internal function]: Foil\\Template\\Template->run('alerts')
#27 /mnt/external/www/ixpmanager/vendor/foil/foil/src/Template/Template.php(102): call_user_func_array(Array, Array)
#28 /mnt/external/www/ixpmanager/resources/views/auth/login.foil.php(12): Foil\\Template\\Template->__call('alerts', Array)
#29 /mnt/external/www/ixpmanager/vendor/foil/foil/src/Template/Template.php(287): require('/mnt/external/w...')
#30 /mnt/external/www/ixpmanager/vendor/foil/foil/src/Template/Template.php(231): Foil\\Template\\Template->collect('/mnt/external/w...')
#31 /mnt/external/www/ixpmanager/vendor/foil/foil/src/Engine.php(307): Foil\\Template\\Template->render(Array)
#32 /mnt/external/www/ixpmanager/vendor/foil/foil/src/Engine.php(231): Foil\\Engine->doRender('/mnt/external/w...', Array, NULL)
#33 /mnt/external/www/ixpmanager/vendor/foil/foil/src/Engine.php(204): Foil\\Engine->renderTemplate('/mnt/external/w...', Array)
#34 /mnt/external/www/ixpmanager/app/Services/FoilEngine.php(51): Foil\\Engine->render('/mnt/external/w...', Array)
#35 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/View/View.php(143): IXP\\Services\\FoilEngine->get('/mnt/external/w...', Array)
#36 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\\View\\View->getContents()
#37 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#38 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#39 /mnt/external/www/ixpmanager/vendor/symfony/http-foundation/Response.php(205): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#40 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Router.php(749): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View), 200, Array)
#41 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#42 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#43 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /mnt/external/www/ixpmanager/app/Http/Middleware/RedirectIfAuthenticated.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): IXP\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /mnt/external/www/ixpmanager/app/Http/Middleware/ControllerEnabled.php(96): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): IXP\\Http\\Middleware\\ControllerEnabled->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#62 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#63 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#64 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#65 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#66 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#67 /mnt/external/www/ixpmanager/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#79 /mnt/external/www/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#80 /mnt/external/www/ixpmanager/public/index.php(85): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#81 {main}`

**Comment by barryo** [comment]
Hi @gizmo15 - can you run the following in your IXP Manager install directory please:

**Careful - an rm -rf lives here:**

```sh
rm -rf vendor
composer install --no-dev --prefer-dist
```

**Comment by gizmo15** [comment]
Same error :
[2021-03-04 20:04:10] production.ERROR: Array and string offset access syntax with curly braces is deprecated {"exception":"[object] (ErrorException(code: 0): Array and string offset access syntax with curly braces is deprecated at /mnt/external/www/ixpmanager/vendor/ezyang/htmlpurifier/library/HTMLPurifier/TagTransform/Font.php:78)

**Comment by barryo** [comment]
Have you skinned any of the template files?

Anything other changes from an absolute by the book basic install?

**Comment by barryo** [comment]
Can you also provide the version from `cat version.php` please?

And the output of `git status` please?

**Comment by gizmo15** [comment]
i just customize the .env file.

[root@ns /mnt/external/www/ixpmanager]# cat version.php
<?php

/*
 * Copyright (C) 2009 - 2019 Internet Neutral Exchange Association Company Limited By Guarantee.
 * All Rights Reserved.
 *
 * This file is part of IXP Manager.
 *
 * IXP Manager is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, version v2.0 of the License.
 *
 * IXP Manager is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GpNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License v2.0
 * along with IXP Manager.  If not, see:
 *
 * http://www.gnu.org/licenses/gpl-2.0.html
 */

#
# Basic version information
#

define( 'APPLICATION_VERSION', '5.7.0' );
define( 'APPLICATION_VERDATE', '2020082000' );

And i use this archive :
https://github.com/inex/IXP-Manager/archive/v5.7.0.tar.gz

**Comment by barryo** [comment]
The archive should be fine but it's not really the recommended way to install. A git clone and use branch `release-v5` would be better and provide an upgrade path. There's no documented upgrade path from the archive files.

What's happening is you've tripped over a piece of code in a third party library / vendor file that is not compatible with PHP 7.4. I suspect if you downgraded to 7.3 this would work fine.

What's confusing for me is that we don't trip over this code on the login page of a default install ourselves so I'm really not sure how it is that you're triggering it. Can you diff your .env to the .env.example and remove any sensitive info and post here?

**Comment by gizmo15** [comment]
I can reinstall from git if it's a part of the problem!

[root@ns /mnt/external/www/ixpmanager]# diff .env .env.sample
8c8
< APP_KEY=
---
> APP_KEY=
18c18
< APP_URL="https://manager.XXXX"
---
> APP_URL="https://ixp.example.com"
33,35c33,35
< DB_DATABASE="ixpmanager"
< DB_USERNAME="ixpmanager"
< DB_PASSWORD="XXXXXXX"
---
> DB_DATABASE="ixp"
> DB_USERNAME="ixp"
> DB_PASSWORD="password"
47c47
< IDENTITY_SITENAME="XXXXX Manager"
---
> IDENTITY_SITENAME="Vagrant IXP Manager"
52,54c52,54
< IDENTITY_LEGALNAME="XXXXXX"
< IDENTITY_CITY="XXXXXX"
< IDENTITY_COUNTRY="FR"
---
> IDENTITY_LEGALNAME="Vagrant City IXP"
> IDENTITY_CITY="Dublin"
> IDENTITY_COUNTRY="IE"
59c59
< IDENTITY_EMAIL="contact@XXXXXX"
---
> IDENTITY_EMAIL="ixp@example.com"
64c64
< IDENTITY_WATERMARK="XXXXXX"
---
> IDENTITY_WATERMARK="Vagrant City IXP"
75c75
< IDENTITY_CORPORATE_URL="https://www.XXXXXX"
---
> IDENTITY_CORPORATE_URL="http://www.example.com/"
79c79
< IDENTITY_BIGLOGO="//www.XXXXXXXX/uploads/logo-1.png"
---
> IDENTITY_BIGLOGO="//www.ixpmanager.org/images/logos/ixp-manager.png"
284a285,286
>
>

i can't downgrade because i have another product who need php 7.4

**Comment by gizmo15** [comment]
i use the git install and i have the same result :

`[2021-03-04 21:02:41] production.ERROR: Array and string offset access syntax with curly braces is deprecated {"exception":"[object] (ErrorException(code: 0): Array and string offset access syntax with curly bra
ces is deprecated at /mnt/external/www/ixpmanager-git/vendor/ezyang/htmlpurifier/library/HTMLPurifier/TagTransform/Font.php:78)`

`[root@ns /mnt/external/www/ixpmanager-git/storage/logs]# git status
On branch release-v5
Your branch is up to date with 'origin/release-v5'.

nothing to commit, working tree clean`

**Comment by barryo** [comment]
Too quick @gizmo15 - I didn't want to ask you to install from Git without knowing something would be different.

I just pushed some updates that removes that third party middleware dependancy and updates the actual required library to a version that supports 7.4.

Can you:

```
git checkout release-v5
git pull
composer install --no-dev --prefer-dist
```

and see how you get on?

I'll follow up tomorrow if it does not work.

**Comment by gizmo15** [comment]
i still have the first installation in another folder ;)

thanks for the update, it work! (now i have a wrong password but it's another problem :p)
